### GET Comment
GET http://localhost:3000/comments

### POST comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "text": "New comment"
}

### GET comment by id
GET http://localhost:3000/comments/4


### PATCH updating comment by id
PATCH http://localhost:3000/comments/3
Content-Type: application/json

{
    "text": "Updated comment"
}

### DELETE comment by id
DELETE http://localhost:3000/comments/3

###
GET http://localhost:3000/profile/api
Authorization: Bearer 12345