export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// This layout serve as the top most layout or the root layout
// It is the mandatory layout for the nextjs application
// https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Every layout component should accept the children props, that will be replaced by the child component during rendering.
  // EX: './page.tsx' component will replaced the child props when the layout is rendered on the browser.
  return (
    <html lang="en">
      <body>
        {/* Adding header component inside layout */}
        {/* These header and footer component will be visible and are Shared UI component to every child component page */}
        <header>
          <h1>Header Layout</h1>
        </header>
        {children}
        {/* Adding footer component */}
        <footer>
          <h1>Footer Layout</h1>
        </footer>
      </body>
    </html>
  );
}
