import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    // https://nextjs.org/docs/app/api-reference/functions/generate-metadata#title
    default: "Next.js Child route", // fallback title for child routes segments, if you don't explicitly provide title on child routes
    template: "%s | Roman", // title.template can be used to add a prefix or a suffix to titles defined in child route segments. it doesn't add on the route segment where it is defined
    // %s is the title of child route
    absolute: "", // 'title.absolute' can be used to provide a title that ignores 'title.template' set in parent route segments.
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Header</h1>
        </header>
        {children}
        <footer>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
